name: Bazel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bazel
        uses: bazelbuild/setup-bazel@v4
        with:
          bazel-version: '8.1.0'
          
      - name: Configure C++ environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential xorg-dev libgl1-mesa-dev

      - name: Build with Bazel
        run: bazel build //...

      - name: Run Tests with Bazel
        run: bazel test //...
