name: Bazel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      - name: Configure C++ environment (Ubuntu only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential xorg-dev libgl1-mesa-dev

      - name: Build with Bazel
        run: |
          bazel build //... ${{ (runner.os == 'macOS') && '--repo_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1' || '' }}

      - name: Run Tests with Bazel
        run: |
          bazel test //... ${{ (runner.os == 'macOS') && '--repo_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1' || '' }}